name = "destaques"
compatibility_date = "2025-11-13"

# 1. Aponte para o script que acabamos de criar.
#    (Ajuste o caminho se você colocou em /src/index.js)
main = "index.js"

# 2. Em vez de [site], definimos a pasta "dist" como uma variável
#    que o script "index.js" pode acessar.
[vars]
ASSETS = { binding_type = "kv_namespace", id = "destaques" }

# 3. Esta parte é necessária para VINCULAR a pasta "dist"
#    à variável ASSETS.
[[kv_namespaces]]
binding = "ASSETS"
id = "destaques"
preview_id = "destaques_preview"
bucket = "./dist" # <-- A pasta que seu build cria